version: "3"
services:
  database:
    image: postgres:11-alpine
    environment:
       - POSTGRES_DB=helpme
       - POSTGRES_USER=helpme_user
       - POSTGRES_PASSWORD=helpme_pass
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
